---
<<<<<<< HEAD
java_jdk_version: 11.0.14
java_oracle_jdk_package: jdk-11.0.14_linux-x64_bin.tar.gz
=======
java_jdk_version: 11.0.12
java_oracle_jdk_package: "jdk-{{ java_jdk_version }}_linux-x64_bin.tar.gz"
>>>>>>> 762134a (bump jdk version)
