---
all:
  hosts:
    sonar-01:
      ansible_host: 178.154.209.230
      ansible_user: aragast
  children:
    sonarqube:
      hosts:
        sonar-01:
    nexus:
      hosts:
        nexus-01:
          ansible_host: 178.154.233.219
          ansible_user: aragast
    postgres:
      hosts:
        sonar-01:
  vars:
    ansible_connection_type: paramiko